# Generated by Django 5.2.5 on 2025-09-01 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_job_description_and_more'),
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescriptiontext',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apply_description', to='application.application'),
        ),
    ]
