# Generated by Django 5.2.5 on 2025-09-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0002_jobdescriptiontext_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescriptiontext',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
