# Generated by Django 5.2.5 on 2025-09-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(max_length=255)),
                ('salary_eur_min', models.FloatField(blank=True, null=True)),
                ('salary_eur_max', models.FloatField(blank=True, null=True)),
                ('bonus_percent', models.FloatField(blank=True, null=True)),
                ('benefits', models.JSONField(blank=True, null=True)),
                ('years_experience_min', models.IntegerField(blank=True, null=True)),
                ('years_experience_max', models.IntegerField(blank=True, null=True)),
                ('education_required', models.TextField(blank=True, null=True)),
                ('responsibilities', models.JSONField(blank=True, null=True)),
                ('required_core_skills', models.JSONField(blank=True, null=True)),
                ('desirable_skills', models.JSONField(blank=True, null=True)),
                ('programming_languages', models.JSONField(blank=True, null=True)),
                ('frameworks_tools', models.JSONField(blank=True, null=True)),
                ('databases', models.JSONField(blank=True, null=True)),
                ('cloud_platforms', models.JSONField(blank=True, null=True)),
                ('api_protocols', models.JSONField(blank=True, null=True)),
                ('methodologies', models.JSONField(blank=True, null=True)),
                ('mobile_technologies', models.JSONField(blank=True, null=True)),
                ('domain_keywords', models.JSONField(blank=True, null=True)),
                ('remote_work', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('on-site', 'On-Site')], max_length=20, null=True)),
                ('work_permit_required', models.BooleanField(null=True)),
                ('visa_sponsorship', models.BooleanField(null=True)),
                ('contact_person', models.CharField(max_length=255, null=True)),
                ('contact_email_or_phone', models.CharField(max_length=255, null=True)),
                ('industry', models.CharField(max_length=255, null=True)),
                ('language_requirements', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
