# Generated by Django 5.2.5 on 2025-08-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='applied', max_length=20)),
                ('stage_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
