# Generated by Django 5.2.5 on 2025-09-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job_description',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('prepared', 'Prepared'), ('applied', 'Applied'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
