# Generated by Django 5.2.5 on 2025-09-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='job_text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_description', to='application.jobdescriptiontext'),
        ),
    ]
