# Generated by Django 5.2.5 on 2025-09-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_options_application_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='employment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
